#include "Types.h"

const double matrix[18][18] = {
	//            Normal		Kampf			Flug			Gift			Boden			Stein			Käfer			Geist			Stahl			Feuer			Wasser			Pflanze			Elektro			Psycho			Eis				Drache			Unlicht				Kein Typ
	/* Normal*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_IMMUN	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Kampf*/	 {EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_IMMUN	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_SEHR		,EFFEKT_NORM },
	/* Flug*/	 {EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Gift*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_IMMUN	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Boden*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_IMMUN	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Gestein*/ {EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Käfer*/	 {EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR		,EFFEKT_NORM },
	/* Geist*/	 {EFFEKT_IMMUN	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT		,EFFEKT_NORM },
	/* Stahl*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Feuer*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Wasser*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Pflanze*/ {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Elektro*/ {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_IMMUN	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Psycho*/	 {EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_IMMUN		,EFFEKT_NORM },
	/* Eis*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_SEHR	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Drache*/	 {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM		,EFFEKT_NORM },
	/* Unlicht*/ {EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NICHT	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_SEHR	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NICHT		,EFFEKT_NORM },

	/* Kein Typ*/{EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM    ,EFFEKT_NORM    ,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM	,EFFEKT_NORM		,EFFEKT_NORM }

};

double getMultiplikator(int attackType, int defenseType1, int defenseType2){

	return (matrix[attackType][defenseType1])*(matrix[attackType][defenseType2]);

}